proyectoinsectos/config/routes.rb
Rails.application.routes.draw do
  resources :peliculas
  resources :usuarios

  root 'peliculas#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

proyectoinsectos/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

proyectoinsectos/app/models/pelicula.rb
class Pelicula
  include Mongoid::Document
  field :nombre, type: String
  field :año, type: Date
  field :synopsis, type: String
  field :categoria, type: String
  field :calidad, type: String
  field :url, type: String
end

proyectoinsectos/app/models/usuario.rb
class Usuario
  include Mongoid::Document
  include Mongoid::Timestamps

  field :usuario, type: String
  field :contraseña, type: String
  field :nombres, type: String
  field :apellidos, type: String
  field :correo, type: String
  field :edad, type: Integer
end

proyectoinsectos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

proyectoinsectos/app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
  before_action :set_pelicula, only: [:show, :edit, :update, :destroy]

  # GET /peliculas
  # GET /peliculas.json
  def index
    @peliculas = Pelicula.all
  end

  # GET /peliculas/1
  # GET /peliculas/1.json
  def show
  end

  # GET /peliculas/new
  def new
    @pelicula = Pelicula.new
  end

  # GET /peliculas/1/edit
  def edit
  end

  # POST /peliculas
  # POST /peliculas.json
  def create
    @pelicula = Pelicula.new(pelicula_params)

    respond_to do |format|
      if @pelicula.save
        format.html { redirect_to @pelicula, notice: 'Pelicula was successfully created.' }
        format.json { render :show, status: :created, location: @pelicula }
      else
        format.html { render :new }
        format.json { render json: @pelicula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peliculas/1
  # PATCH/PUT /peliculas/1.json
  def update
    respond_to do |format|
      if @pelicula.update(pelicula_params)
        format.html { redirect_to @pelicula, notice: 'Pelicula was successfully updated.' }
        format.json { render :show, status: :ok, location: @pelicula }
      else
        format.html { render :edit }
        format.json { render json: @pelicula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peliculas/1
  # DELETE /peliculas/1.json
  def destroy
    @pelicula.destroy
    respond_to do |format|
      format.html { redirect_to peliculas_url, notice: 'Pelicula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pelicula
      @pelicula = Pelicula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pelicula_params
      params.require(:pelicula).permit(:nombre, :año, :synopsis, :categoria, :calidad, :url)
    end
end

proyectoinsectos/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:usuario, :contraseña, :nombres, :apellidos, :correo, :edad)
    end
end

proyectoinsectos/app/helpers/application_helper.rb
module ApplicationHelper
end

proyectoinsectos/app/helpers/peliculas_helper.rb
module PeliculasHelper
end

proyectoinsectos/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

proyectoinsectos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyectoinsectos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

proyectoinsectos/app/views/peliculas/_form.html.erb
<%= form_with(model: pelicula, local: true) do |form| %>
  <% if pelicula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pelicula.errors.count, "error") %> prohibited this pelicula from being saved:</h2>

      <ul>
      <% pelicula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :año %>
    <%= form.text_field :año %>
  </div>

  <div class="text_area">
    <%= form.label :synopsis %>
    <%= form.text_area :synopsis %>
  </div>

  <div class="field">
    <%= form.label :categoria %>
    <%= form.text_field :categoria %>
  </div>

  <div class="field">
    <%= form.label :calidad %>
    <%= form.text_field :calidad %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

proyectoinsectos/app/views/peliculas/edit.html.erb
<h1>Editing Pelicula</h1>

<%= render 'form', pelicula: @pelicula %>

<%= link_to 'Show', @pelicula %> |
<%= link_to 'Back', peliculas_path %>

proyectoinsectos/app/views/peliculas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Peliculas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Año</th>
      <th>Synopsis</th>
      <th>Categoria</th>
      <th>Calidad</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peliculas.each do |pelicula| %>
      <tr>
        <td><%= pelicula.nombre %></td>
        <td><%= pelicula.año %></td>
        <td><%= pelicula.synopsis %></td>
        <td><%= pelicula.categoria %></td>
        <td><%= pelicula.calidad %></td>
        <td><%= pelicula.url %></td>
        <td><%= link_to 'Show', pelicula %></td>
        <td><%= link_to 'Edit', edit_pelicula_path(pelicula) %></td>
        <td><%= link_to 'Destroy', pelicula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pelicula', new_pelicula_path %>

proyectoinsectos/app/views/peliculas/new.html.erb
<h1>New Pelicula</h1>

<%= render 'form', pelicula: @pelicula %>

<%= link_to 'Back', peliculas_path %>

proyectoinsectos/app/views/peliculas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @pelicula.nombre %>
</p>

<p>
  <strong>Año:</strong>
  <%= @pelicula.año %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @pelicula.synopsis %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @pelicula.categoria %>
</p>

<p>
  <strong>Calidad:</strong>
  <%= @pelicula.calidad %>
</p>

<p>
  <strong>Url:</strong>
  <%= @pelicula.url %>
</p>

<%= link_to 'Edit', edit_pelicula_path(@pelicula) %> |
<%= link_to 'Back', peliculas_path %>

proyectoinsectos/app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :usuario %>
    <%= form.text_field :usuario %>
  </div>

  <div class="field">
    <%= form.label :contraseña %>
    <%= form.text_field :contraseña %>
  </div>

  <div class="field">
    <%= form.label :nombres %>
    <%= form.text_field :nombres %>
  </div>

  <div class="field">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_field :correo %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.text_field :edad %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

proyectoinsectos/app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

proyectoinsectos/app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Contraseña</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Correo</th>
      <th>Edad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.usuario %></td>
        <td><%= usuario.contraseña %></td>
        <td><%= usuario.nombres %></td>
        <td><%= usuario.apellidos %></td>
        <td><%= usuario.correo %></td>
        <td><%= usuario.edad %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

proyectoinsectos/app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

proyectoinsectos/app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @usuario.usuario %>
</p>

<p>
  <strong>Contraseña:</strong>
  <%= @usuario.contraseña %>
</p>

<p>
  <strong>Nombres:</strong>
  <%= @usuario.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @usuario.apellidos %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @usuario.correo %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @usuario.edad %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>